service: rest-api

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 30

functions:
  nano-user-get:
    handler: handler.getUser
    events:
      - http: GET nano/users
  nano-user-delete:
    handler: handler.deleteUser
    events:
      - http: DELETE nano/users
  nano-cart-get:
    handler: handler.getCart
    events:
      - http: GET nano/carts
  nano-cart-delete:
    handler: handler.deleteCart
    events:
      - http: DELETE nano/carts
  micro-user:
    handler: handler.users
    events:
      - http: GET micro/users
      - http: DELETE micro/users
  micro-cart:
    handler: handler.carts
    events:
      - http: GET micro/carts
      - http: DELETE micro/carts
  monolith:
    handler: handler.all
    events:
      - http: GET monolith/users
      - http: DELETE monolith/users
      - http: GET monolith/carts
      - http: DELETE monolith/carts
