service: step-functions

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - states:StartExecution
      Resource:  ${self:resources.Outputs.TrafficLightStateMachineARN.Value}

functions:
  entrypoint:
    handler: handler.entrypoint
    environment:
          STATE_MACHINE_ARN: { "Ref": "TrafficLightStateMachine" }
    events:
      - http:
          path: trafficlight
          method: get
          cors: true
          private: false
  on-red:
    handler: handler.red
  on-green:
    handler: handler.green
  on-yellow:
    handler: handler.yellow
  on-response:
    handler: handler.response

stepFunctions:
  stateMachines:
    TrafficLightStateMachine:
      name: TrafficLightStateMachine
      definition:
        Comment: "An example of the Amazon States Language"
        StartAt: ReadState
        States:
          ReadState:
            Type: Choice
            Choices:
            - Variable: "$.color"
              StringEquals: "red"
              Next: RedState
            - Variable: "$.color"
              StringEquals: "yellow"
              Next: YellowState
            - Variable: "$.color"
              StringEquals: "green"
              Next: GreenState
            Default: DefaultState
          RedState:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-on-red
            Next: WaitState
          GreenState:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-on-green
            Next: WaitState
          YellowState:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-on-yellow
            Next: WaitState
          WaitState:
            Type: Wait
            TimestampPath: "$.wait"
            Next: ResponseState
          DefaultState:
            Type: Fail
            Cause: "No Color Matches!"
          ResponseState:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-on-response
            End: true

resources:
  Outputs:
    TrafficLightStateMachineARN:
      Description: The ARN of the Traffic Light state machine
      Value:
        Ref: TrafficLightStateMachine