service: graphql

custom:
  dbTable: ${self:service}-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - { "Fn::GetAtt": ["DbTable", "Arn" ] }

functions:
  graphql:
    handler: handler.graphql
    environment:
      DB_TABLE: { "Ref": "DbTable" }
    events:
      - http:
          path: graphql
          method: GET

resources:
  Resources: 
    DbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: key
            AttributeType: S
        KeySchema:
          -
            AttributeName: key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: '${self:custom.dbTable}'
