service: streams

custom:
  dbTable: ${self:service}-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - { "Fn::GetAtt": ["DbTable", "Arn" ] }
        
functions:
  dynamo-add:
    handler: handler.dynamoAdd
    environment:
      DB_TABLE: { "Ref": "DbTable" }
  dynamo-listener:
    handler: handler.dynamoListener
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - DbTable
              - StreamArn

resources:
  Resources: 
    DbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: '${self:custom.dbTable}'
        StreamSpecification:
          StreamViewType: NEW_IMAGE