service: events

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 30

functions:
  cron:
    handler: handler.cron
    events:
      - schedule: rate(1 minute)
  api:
    handler: handler.api
    events:
      - http:
          path: lambda/hello
          method: GET
  # log:
  #   handler: handler.log
  #   events:
  #     - cloudwatchLog: '/aws/lambda/events-dev-cron'