service: manage-secrets # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 30
  stage: dev
  region: eu-west-1
  environment:
    GLOBAL_API_KEY: XYZ

functions:
  hello:
    handler: handler.hello
    environment:
      LAMBDA_API_KEY: ZZZ
